branch-defaults:
  master:
    environment: braintree-env
global:
  application_name: braintree
  default_ec2_keyname: test
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
